alter table ANKETIROVANIE_QUESTION_ANSWER_LINK add constraint FK_QUEANS_ON_QUESTION foreign key (QUESTION_ID) references ANKETIROVANIE_QUESTION(ID);
alter table ANKETIROVANIE_QUESTION_ANSWER_LINK add constraint FK_QUEANS_ON_ANSWER foreign key (ANSWER_ID) references ANKETIROVANIE_ANSWER(ID);
