-- begin ANKETIROVANIE_ANSWER
create unique index IDX_ANKETIROVANIE_ANSWER_UNIQ_ANSWER on ANKETIROVANIE_ANSWER (ANSWER) ^
-- end ANKETIROVANIE_ANSWER
-- begin ANKETIROVANIE_QUESTION
create unique index IDX_ANKETIROVANIE_QUESTION_UNIQ_QUESTION on ANKETIROVANIE_QUESTION (QUESTION) ^
-- end ANKETIROVANIE_QUESTION
-- begin ANKETIROVANIE_QUESTIONNAIRE
create unique index IDX_ANKETIROVANIE_QUESTIONNAIRE_UNIQ_QUESTIONNAIRE on ANKETIROVANIE_QUESTIONNAIRE (QUESTIONNAIRE) ^
-- end ANKETIROVANIE_QUESTIONNAIRE
-- begin ANKETIROVANIE_QUESTION_ANSWER_LINK
alter table ANKETIROVANIE_QUESTION_ANSWER_LINK add constraint FK_QUEANS_ON_QUESTION foreign key (QUESTION_ID) references ANKETIROVANIE_QUESTION(ID)^
alter table ANKETIROVANIE_QUESTION_ANSWER_LINK add constraint FK_QUEANS_ON_ANSWER foreign key (ANSWER_ID) references ANKETIROVANIE_ANSWER(ID)^
-- end ANKETIROVANIE_QUESTION_ANSWER_LINK
-- begin ANKETIROVANIE_QUESTIONNAIRE_QUESTION_LINK
alter table ANKETIROVANIE_QUESTIONNAIRE_QUESTION_LINK add constraint FK_QUEQUE_ON_QUESTIONNAIRE foreign key (QUESTIONNAIRE_ID) references ANKETIROVANIE_QUESTIONNAIRE(ID)^
alter table ANKETIROVANIE_QUESTIONNAIRE_QUESTION_LINK add constraint FK_QUEQUE_ON_QUESTION foreign key (QUESTION_ID) references ANKETIROVANIE_QUESTION(ID)^
-- end ANKETIROVANIE_QUESTIONNAIRE_QUESTION_LINK
